/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package biotracker;

/**
 *
 * @author glenn
 */
public class MainGUI extends javax.swing.JFrame {
    
    private DataManager manager = new DataManager();
    private int idCounter = 1; // This will keep track of IDs
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainGUI.class.getName());

    /**
     * Creates new form MainGUI
     */
    public MainGUI() {
        initComponents();
        
        txtId.setText(String.format("REC-%03d", idCounter));
    }
    
    private void refreshDisplay() {
        txtDisplay.setText(""); // Clear the text area first
        
        // Loop through the main ArrayList and display all verified records
        for (EcoRecord record : manager.getAllRecords()) {
            // Polymorphism in action! It calls the right displayDetails() automatically
            txtDisplay.append(record.displayDetails() + "\n"); 
        }
        
        // Show how many are waiting in the Queue
        txtDisplay.append("\n--- Pending in Queue: " + manager.getPendingCount() + " ---");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtLocation = new javax.swing.JTextField();
        txtDate = new javax.swing.JTextField();
        txtHealthBehaviour = new javax.swing.JTextField();
        cmbRecordType = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtSpeciesAnimal = new javax.swing.JTextField();
        btnUndo = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnApproveNext = new javax.swing.JButton();
        btnSubmitQueue = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDisplay = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Record ID:");

        txtId.setEditable(false);
        txtId.setBackground(new java.awt.Color(204, 204, 204));

        jLabel2.setText("Location:");

        jLabel3.setText("Date (YYYY-MM-DD):");

        jLabel4.setText("Health / Behaviour:");

        cmbRecordType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Flora", "Fauna" }));

        jLabel5.setText("Record Type:");

        jLabel6.setText("Species / Animal:");

        btnUndo.setText("Undo Delete");

        btnDelete.setText("Delete Record");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnApproveNext.setText("Appprove Next");
        btnApproveNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApproveNextActionPerformed(evt);
            }
        });

        btnSubmitQueue.setText("Submit to Queue");
        btnSubmitQueue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitQueueActionPerformed(evt);
            }
        });

        txtDisplay.setColumns(20);
        txtDisplay.setRows(5);
        jScrollPane1.setViewportView(txtDisplay);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtId)
                            .addComponent(txtHealthBehaviour)
                            .addComponent(txtDate)
                            .addComponent(txtSpeciesAnimal)
                            .addComponent(txtLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbRecordType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnUndo)
                                .addGap(18, 18, 18)
                                .addComponent(btnDelete)
                                .addGap(18, 18, 18)
                                .addComponent(btnApproveNext)))
                        .addGap(18, 18, 18)
                        .addComponent(btnSubmitQueue)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbRecordType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtSpeciesAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtHealthBehaviour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUndo)
                    .addComponent(btnDelete)
                    .addComponent(btnApproveNext)
                    .addComponent(btnSubmitQueue))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitQueueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitQueueActionPerformed
        // TODO add your handling code here:
        // Gather text from the text fields
        String id = txtId.getText();
        String loc = txtLocation.getText();
        String date = txtDate.getText();
        String typeOrSpecies = txtSpeciesAnimal.getText();
        String healthOrBehaviour = txtHealthBehaviour.getText();
        
        // Check the Dropdown to see if it's Flora or Fauna
        String recordType = cmbRecordType.getSelectedItem().toString();
        
        EcoRecord newRecord;
        
        if (recordType.equals("Flora")) {
            newRecord = new FloraRecord(id, loc, date, typeOrSpecies, healthOrBehaviour);
        } else {
            newRecord = new FaunaSighting(id, loc, date, typeOrSpecies, healthOrBehaviour);
        }
        
        // Add to the Queue via the DataManager
        manager.addRecord(newRecord);
        refreshDisplay();
        
        // Increase the counter and update the grey box for the next record
        idCounter++;
        txtId.setText(String.format("REC-%03d", idCounter));
        
        // Clear the text fields for the next entry
        txtLocation.setText("");
        txtDate.setText("");
        txtSpeciesAnimal.setText("");
        txtHealthBehaviour.setText("");
        
        // show a popup message
        javax.swing.JOptionPane.showMessageDialog(this, "Successfully added to the Pending Queue!");
    }//GEN-LAST:event_btnSubmitQueueActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        //  pop up asking for the ID
        String idToDelete = javax.swing.JOptionPane.showInputDialog(this, "Enter the Record ID to delete (e.g., REC-001):");
        
        // Check if clicked Cancel or left it blank
        if (idToDelete == null || idToDelete.trim().isEmpty()) {
            return; // Just cancel the action
        }
        
        // delete it and store the result (true/false)
        boolean success = manager.deleteRecord(idToDelete.trim());
        
        // Show the correct pop up based on the result
        if (success) {
            javax.swing.JOptionPane.showMessageDialog(this, "Success! Record " + idToDelete + " has been deleted.");
            refreshDisplay(); // Only refresh if something actually changed
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: Record '" + idToDelete + "' does not exist.", "Not Found", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnApproveNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApproveNextActionPerformed
        // TODO add your handling code here:
        // Peek at the next record in line
        EcoRecord nextRecord = manager.peekNextPending();
        
        // Check if the queue is empty
        if (nextRecord == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "The pending queue is empty. No records to approve.", "Queue Empty", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            return; // Stop running the code
        }
        
        // Show a confirmation pop up with the record details
        int choice = javax.swing.JOptionPane.showConfirmDialog(this, 
                "Do you want to approve the following record?\n\n" + nextRecord.displayDetails(), 
                "Review Pending Record", 
                javax.swing.JOptionPane.YES_NO_OPTION, 
                javax.swing.JOptionPane.QUESTION_MESSAGE);
        
        // If they click Yes, actually dequeue it and approve it
        if (choice == javax.swing.JOptionPane.YES_OPTION) {
            manager.approveNextPending(); // This officially moves it out of the queue
            refreshDisplay();
            javax.swing.JOptionPane.showMessageDialog(this, "Success! Record " + nextRecord.getRecordId() + " has been added to the main registry.");
        }
    }//GEN-LAST:event_btnApproveNextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApproveNext;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSubmitQueue;
    private javax.swing.JButton btnUndo;
    private javax.swing.JComboBox<String> cmbRecordType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextArea txtDisplay;
    private javax.swing.JTextField txtHealthBehaviour;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtLocation;
    private javax.swing.JTextField txtSpeciesAnimal;
    // End of variables declaration//GEN-END:variables
}
